version: 0.2

phases:
  install:
    commands:
      - cd frontend/auth-app
      - npm install
  build:
    commands:
      - npm run build  
artifacts:
  files:
    - '**/*'
  base-directory: frontend/auth-app/build #test
